Configuração e implementação do Room
Bootcamp-CS-Time-1/magic-game pull request #22
Opened 2019-09-26 19:29 UTC by thiagomatheusms

Contém:

- Configuração do Room 
- Construção da ViewModel e Repository da CardDetailActivity
- Adicionado a função de 'adicionar' e 'remover' cartas de favoritos

2019-09-26 19:42 UTC, pedrox-hs requested changes

2019-09-26 19:42 UTC, pedrox-hs commented on app/src/main/java/br/com/bootcamp/magicgamecs/features/detail/CardDetailActivity.kt
> +    private val detailViewModel by lazy {
Você pode declarar esse viewmodel no `AppModules.kt` e aqui vc usar a extensão do Koin `viewModel<>()`

2019-09-26 19:42 UTC, pedrox-hs commented on app/src/main/java/br/com/bootcamp/magicgamecs/models/repository/impl/MagicRepositoryDb.kt
> +        cardDao = dataBase.cardDao()
CardDao pode ser provido por injeção de dependencias com o Koin

2019-09-26 19:42 UTC, pedrox-hs commented on app/src/main/java/br/com/bootcamp/magicgamecs/models/repository/impl/MagicRepositoryDb.kt
> +    private class InsertCardAsyncTask(cardDao: CardDao) : AsyncTask<Card, Unit, Unit>() {
Nesses casos de operações assincronas não daria pra usar coroutines?

2019-09-27 17:42 UTC, thiagomatheusms commented on app/src/main/java/br/com/bootcamp/magicgamecs/features/detail/CardDetailActivity.kt
> +    private val detailViewModel by lazy {
Ok, atualizado.

2019-09-27 18:19 UTC, thiagomatheusms commented on app/src/main/java/br/com/bootcamp/magicgamecs/models/repository/impl/MagicRepositoryDb.kt
> +        cardDao = dataBase.cardDao()
Atualizado

2019-09-27 18:19 UTC, thiagomatheusms commented on app/src/main/java/br/com/bootcamp/magicgamecs/models/repository/impl/MagicRepositoryDb.kt
> +    private class InsertCardAsyncTask(cardDao: CardDao) : AsyncTask<Card, Unit, Unit>() {
Atualizado

2019-09-27 18:41 UTC, thiagomatheusms commented
Adicionado novo commit com as alterações propostas por @pedrox-hs + alguns testes de UI na tela de detalhes.

2019-09-27 18:51 UTC, pedrox-hs requested changes

2019-09-27 18:51 UTC, pedrox-hs commented on app/src/androidTest/java/br/com/bootcamp/magicgamecs/MainActivityTest.kt
> +    fun before(){
Essa classe não está testando nada da MainActivity

2019-09-27 18:51 UTC, pedrox-hs commented on app/src/main/java/br/com/bootcamp/magicgamecs/models/repository/impl/MagicRepositoryDb.kt
> +//    fun getAllFavoritesCards() = cardDao.loadAllCards()
A classe está totalmente comentada, se não está utilizando no projeto acredito que possa ser removida

2019-09-27 19:45 UTC, thiagomatheusms commented on app/src/main/java/br/com/bootcamp/magicgamecs/models/repository/impl/MagicRepositoryDb.kt
> +//    fun getAllFavoritesCards() = cardDao.loadAllCards()
Sim, já tinha verificado isso, vou mandar um novo PR

2019-09-30 14:35 UTC, EribertoJunior approved these changes

2019-09-30 14:36 UTC, pedrox-hs approved these changes

2019-09-30 14:36 UTC, merged